### ISSUE TITLE
Action does not properly handle rebases

### ISSUE THREAD

**Issue by nwiltsie** [uclahs-cds/tool-PlantUML-action#3]
> I added a plantuml figure (among many other revisions) to this repo while a dependabot PR was in place.   After merging all other branches I went to rebase the dependabot branch, `@dependabot rebase` and it failed the plantuml action: [fatal: Invalid revision range d1c56e3ab79e4534a825b8e19f3c5d1bf339edd9..9d914328d0782e17f7c41257e9cc2131734c174b
Error: Process completed with exit code 128.](https://github.com/uclahs-cds/pipeline-SQC-DNA/actions/runs/8205736455/job/22443274788#step:2:520:~:text=fatal%3A%20Invalid%20revision,exit%20code%20128.).  I tried rebase a second time which also failed, then `@dependabot recreate` which was successful.  

> Is this something that shouldn't happen and can be fixed.  Or should I just add the situation to the instructions at [Dependabot Pull Request Protocol](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/206602241/Dependabot+Pull+Request+Protocol+DRAFT)

_Originally posted by @sorelfitzgibbon in https://github.com/uclahs-cds/pipeline-SQC-DNA/issues/22#issuecomment-1985977649_

**Comment by nwiltsie** [comment]
Here are the two unrelated commmits:

https://github.com/uclahs-cds/pipeline-SQC-DNA/commit/d1c56e3ab79e4534a825b8e19f3c5d1bf339edd9
https://github.com/uclahs-cds/pipeline-SQC-DNA/commit/9d914328d0782e17f7c41257e9cc2131734c174b

**Comment by aholmes** [comment]
From [Nick's comment](https://github.com/uclahs-cds/pipeline-SQC-DNA/pull/22#issuecomment-1986014158):
> @sorelfitzgibbon In the best case, this came up because `main` acquired a PlantUML image between when this PR was opened and when you rebased it, which is a relatively uncommon case.

This is essentially what happened.

1. The `checkout` action clones a repository in whatever state it's in when it does so
2. The PlantUML action is given a Git commit SHA that represents the change prior to the commit that triggered the action. This was `d1c56e3ab79e4534a825b8e19f3c5d1bf339edd9` (the now-invalid commit).
3. The PlantUML action attempts to find differences between the previous, now invalid, commit and the current `HEAD`.
4. The action errors because the commit SHA no longer exists.

We can see the steps play out by examining the comments in this PR and the action log:

1. At `2024-03-08T15:52:03Z` Sorel [told Dependabot to rebase](https://github.com/uclahs-cds/pipeline-generate-SQC-BAM/pull/22#issuecomment-1985936565).
2. At `2024-03-08T15:52:26Z` Dependabot [force-pushed](https://github.com/uclahs-cds/pipeline-generate-SQC-BAM/pull/22#event-12057434323) commit [d1c56e3ab79e4534a825b8e19f3c5d1bf339edd9](https://github.com/uclahs-cds/pipeline-generate-SQC-BAM/compare/d1c56e3ab79e4534a825b8e19f3c5d1bf339edd9..9d914328d0782e17f7c41257e9cc2131734c174b) (the now-invalid commit)
3. At `2024-03-08T15:52:28Z`, the [failed action](https://github.com/uclahs-cds/pipeline-generate-SQC-BAM/actions/runs/8205736455) started.
4. At `2024-03-08T15:52:40Z` the repository is "cloned."
5. At `2024-03-08T15:52:41Z` the action errored.

The problem seems to be with #2, in that the previous commit SHA GitHub gives to the action is no longer valid.

**Comment by nwiltsie** [comment]
@aholmes does that mean that this will happen every time a rebase occurs in a repository with this action and an image?

**Comment by aholmes** [comment]
I'm wondering about that. I haven't seen this before, but this observation does seem like it would occur every time. I'm not certain whether I missed a specific detail.

**Comment by nwiltsie** [comment]
Wait, why did the workflow even run in the first place?

```yaml
---
name: PlantUML Generation

on:
  push:
    paths:
      - '**.puml'
  workflow_dispatch:
```

The dependabot PR shouldn't have included any PlantUML files...

**Comment by aholmes** [comment]
The rebase includes PUML files (and the PlantUML action addition itself).

**Comment by aholmes** [comment]
I'm considering changing the action to test whether the previous commit SHA is valid and, if it isn't, defaulting to the "every PUML file" mode rather than attempting to include only the PUML files since the last push.

**Comment by nwiltsie** [comment]
There's some weirdness bandying about here - the actual commit itself (https://github.com/uclahs-cds/pipeline-generate-SQC-BAM/commit/9d914328d0782e17f7c41257e9cc2131734c174b) includes no PlantUML files.

Comparing the old/abandoned commit and the new one (https://github.com/uclahs-cds/pipeline-generate-SQC-BAM/compare/d1c56e3ab79e4534a825b8e19f3c5d1bf339edd9..9d914328d0782e17f7c41257e9cc2131734c174b) shows that a PlantUML file was added, but that's not part of _this_ pull request.

I would have thought the workflow filter would care about the changes relative to the mergee-branch (https://github.com/uclahs-cds/pipeline-generate-SQC-BAM/compare/0a5aae07cdb53c7da6977f682f46c0d73f3f5ca0..9d914328d0782e17f7c41257e9cc2131734c174b).

Weird! I agree though, that this is a super-edge case where a new PlantUML file appears in the commits jumped by a rebase. I also agree that including a valid SHA check is fair.

**Comment by aholmes** [comment]
Yeah, I'm not sure I can speak to exactly what's going on there beyond speculation. Observing this shows that there is the possibility that Actions treats a rebase as a big chunk of changes rather than just a rebase. Whether that's true, it should be safe for us to _act_ like that's the case, and code accordingly.

**Comment by nwiltsie** [comment]
Ahh, okay, this isn't a "pull request" workflow, it's just a workflow. There's no concept of a "mergee-branch" (whatever the proper name for that is) - it only has reference to the last known commit, hence why the PlantUML file appears new.

**Comment by aholmes** [comment]
Ah - good point. Yes, this Action considers everything from the last push. So the issue is there. :)

**Comment by aholmes** [comment]
@nwiltsie suggested using https://docs.github.com/en/webhooks/webhook-events-and-payloads#push and the `github.event.commits.added` / `modified` arrays. This would also resolve a significant portion of #2.
